spring.application.name=final-user
springdoc.swagger-ui.path=swagger-ui

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/final_user
spring.datasource.username=postgres
spring.datasource.password=${DB_PG_PWD:postgres}

server.port=8083

external.todo.service.baseurl=http://localhost:8080
